ARG DISTRO
ARG VERSION

FROM $DISTRO:$VERSION

ARG DEBIAN_FRONTEND=noninteractive

RUN apt --fix-missing update && apt upgrade -y && \
    apt install -y --no-install-recommends \
    procps vim less git iproute2 iputils-ping dbus tcpdump systemd

RUN mkdir /deps

WORKDIR /deps
COPY /misc/build-deps-debs.sh build-deps-debs.sh

RUN bash build-deps-debs.sh
RUN dpkg -i */dist/*deb

CMD /bin/systemd
